# Generated by Django 5.2.1 on 2025-05-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_Quarto', models.IntegerField()),
                ('qtd_Hospedes', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Premium', 'Premium'), ('Plus', 'Plus')])),
                ('valor', models.FloatField(max_length=3)),
                ('descricao', models.TextField(max_length=300)),
                ('status', models.BooleanField(choices=[(1, 'Disponivel'), (0, 'Reservado')], default=1)),
                ('img', models.ImageField(upload_to='quarto/')),
            ],
        ),
    ]
