# Generated by Django 5.2.1 on 2025-05-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_quarto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='tipo',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Premium', 'Premium'), ('Plus', 'Plus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='valor',
            field=models.FloatField(),
        ),
    ]
