# Generated by Django 4.2.21 on 2025-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_alter_quarto_status_alter_quarto_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=255)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
