# Generated by Django 5.2.1 on 2025-05-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_atendente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='atendente',
        ),
    ]
